# fly.toml file generated for syrc-bot-vw on 2023-08-15T23:09:08-04:00

app = "syrc-bot-vw"
kill_signal = "SIGINT"
kill_timeout = 5
mounts = []
processes = []

[env]
  PORT = "8080"

[[services]]
  internal_port = 8080
  protocol = "tcp"
